class StateCodeUtil(object):

    STATE_CODE_DATA = {
        'jammu_&_kashmir': '01',
        'himachal_pradesh': '02',
        'punjab': '03',
        'chandigarh': '04',
        'uttarakhand': '05',
        'haryana': '06',
        'delhi': '07',
        'rajasthan': '08',
        'uttar_pradesh': '09',
        'bihar': '10',
        'sikkim': '11',
        'arunachal_pradesh': '12',
        'nagaland': '13',
        'manipur': '14',
        'mizoram': '15',
        'tripura': '16',
        'meghalaya': '17',
        'assam': '18,',
        'west_bengal': '19',
        'jharkhand': '20',
        'orissa': '21',
        'chhattisgarh': '22',
        'madhya_pradesh': '23',
        'gujarat': '24',
        'daman_&_diu': '25',
        'dadra_&_nagar haveli': '26',
        'maharashtra': '27',
        'andhra_pradesh': '28',
        'karnataka': '29',
        'goa': '30',
        'lakshadweep': '31',
        'kerala': '32',
        'tamil_nadu': '33',
        'puducherry': '34',
        'andaman_&_nicobar islands': '35',
        'telengana': '36',
        'andrapradesh(new)': '37',
    }

    @staticmethod
    def get_state_code(state_str):
        return StateCodeUtil.STATE_CODE_DATA[state_str]
